# TODO: fix Error from line 23 sync file class dataBaseSyncer: ('22003', '[22003] [Microsoft][ODBC Microsoft Access
#  Driver]Numeric value out of range  (34) newFarmersMain file savedata object

# TODO:File "E:\Administration agricole\bin\changeMain.py",
#  line 31, in getData self.idNumber.setText(data[0]) TypeError:
#  setText(self, str): argument 1 has unexpected type 'pyodbc.Row'

